Table inventario {
  id integer [pk, increment]
  name varchar
  ean varchar
  //created timestamp
  quantity integer
  localization varchar
}

Table pedido {
  id int [pk]
  finalizado boolean
  user int [ref: > user.id]
}
Table componentes {
  id integer [ref: > pedido.id]
  producto integer [ref: > inventario.id]
  cantidad int
}
Table user {
  id int [pk, increment]
  name varchar
}

