version: '3.8'

services:
  db:
    build: ./db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: seidor_db
      POSTGRES_USER: anonymous_not_seidor_user
      POSTGRES_PASSWORD: tst
    volumes:
      - ./data:/data
      - ./persistence:/var/lib/postgresql/data"



