sequenceDiagram
    participant User
    participant UserApp
    participant LogisticWorker
    participant LogisticWorkerApp
    participant Database
    participant LogisticSystem

    User ->> UserApp: Request
    UserApp ->> LogisticWorkerApp: Sends request
    alt (No stock in database?)
    LogisticWorkerApp -->> UserApp: Notify "No stock available"
    User -->> UserApp: Choose alternative
    UserApp -->> LogisticWorkerApp: Send request
    else (Stock in database)
    LogisticWorkerApp ->> LogisticWorker: Shows Id and position
    LogisticWorker -->> LogisticWorkerApp: Confirms product
    LogisticWorkerApp ->> Database: Subtract product
    Database -->> LogisticWorkerApp: ACK
    LogisticWorker ->> LogisticSystem: Send product
    LogisticSystem -->> LogisticWorker: ACK
    LogisticWorker ->> LogisticWorkerApp: Notify "Send product"
    LogisticWorkerApp ->> UserApp : Notify "Send product"
    UserApp -->> User: Notified
    end
    alt More corrections needed?
    User ->> UserApp: Correct order
    UserApp ->> LogisticWorkerApp: Correct order
    LogisticWorkerApp ->> LogisticSystem: Correct order
    alt Can modify delivery? 
        LogisticSystem -->> LogisticWorkerApp: ACK
    else 
        LogisticSystem -->> LogisticWorkerApp: Notify "Error: Cannot modify if order is out"
        LogisticWorkerApp ->> UserApp : Notify "Error: Cannot modify if order is out"
        UserApp -->> User: Notified Error
    end
    LogisticWorkerApp ->> Database: Adjust database
    Database -->> LogisticWorkerApp: ACK
    alt Database adjustment successful
                LogisticWorkerApp ->> UserApp : Notify "Corrected order"
                UserApp -->> User: Notified
            else Database adjustment failed
                LogisticWorkerApp -->> UserApp : Notify "Error: Database adjustment failed"
                UserApp -->> User: Notified Error
            end
    end
    LogisticSystem ->> UserApp: Package finished
    UserApp -->> User: Notified
